package emit

import (
	"bytes"
	"fmt"
	"go/format"
	"net/textproto"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/P4elme6ka/gen-router/src/codegen/ir"
)

const generatedFileName = "zz_gen_router_meta.go"

const metadataTemplate = `// Code generated by gen-router. DO NOT EDIT.
package {{ .PackageName }}

import (
	"net/http"
	{{- if .NeedsFmt }}
	"fmt"
	{{- end }}
	{{- if .NeedsIO }}
	"io"
	{{- end }}
	{{- if .NeedsStrconv }}
	"strconv"
	{{- end }}
	{{- if .NeedsStrings }}
	"strings"
	{{- end }}
	{{- if .NeedsUUID }}

	"github.com/google/uuid"
	{{- end }}

	genrouterruntime "github.com/P4elme6ka/gen-router/src/codegen/runtime"
)

{{ range .Handlers }}
func {{ binderSymbol . }}(req *http.Request) (any, error) {
	var input {{ .InputType }}
	{{- range binderStatements . }}
	{{ . }}
	{{- end }}
	return input, nil
}

{{ end }}
{{- if .NeedsStrings }}
func splitGeneratedPath(path string) []string {
	trimmed := strings.Trim(path, "/")
	if trimmed == "" {
		return nil
	}
	return strings.Split(trimmed, "/")
}
{{- end }}

{{- if .NeedsIO }}
func reqBodyPresentGenerated(req *http.Request) bool {
	if req.Body == nil {
		return false
	}
	if req.ContentLength > 0 {
		return true
	}
	if req.ContentLength == 0 {
		return false
	}
	return true
}
{{- end }}

{{- if .NeedsUUID }}
func parseGeneratedUUID(raw string) (uuid.UUID, error) {
	return uuid.Parse(raw)
}
{{- end }}

var GenRouterMetadata = genrouterruntime.PackageMetadata{
	ImportPath: {{ printf "%q" .ImportPath }},
	PackageName: {{ printf "%q" .PackageName }},
	Dir: {{ printf "%q" .Dir }},
	Handlers: []genrouterruntime.HandlerMetadata{
		{{- range .Handlers }}
		{
			HandlerType: {{ printf "%q" .HandlerType }},
			InputType: {{ printf "%q" .InputType }},
			OutputType: {{ printf "%q" .OutputType }},
			Route: genrouterruntime.RouteMetadata{
				Method: {{ printf "%q" .Route.Method }},
				Path: {{ printf "%q" .Route.Path }},
			},
			Input: genrouterruntime.InputMetadata{
				Body: {{- if .Input.Body }}&genrouterruntime.InputFieldMetadata{GoName: {{ printf "%q" .Input.Body.GoName }}, Source: {{ printf "%q" .Input.Body.Source }}, Name: {{ printf "%q" .Input.Body.Name }}, Type: {{ printf "%q" .Input.Body.Type }}} {{- else }}nil{{- end }},
				Fields: []genrouterruntime.InputFieldMetadata{
					{{- range .Input.Fields }}
					{GoName: {{ printf "%q" .GoName }}, Source: {{ printf "%q" .Source }}, Name: {{ printf "%q" .Name }}, Type: {{ printf "%q" .Type }}},
					{{- end }}
				},
			},
			Output: genrouterruntime.OutputMetadata{
				SharedFields: []genrouterruntime.OutputFieldMetadata{
					{{- range .Output.SharedFields }}
					{GoName: {{ printf "%q" .GoName }}, Source: {{ printf "%q" .Source }}, Name: {{ printf "%q" .Name }}, Type: {{ printf "%q" .Type }}},
					{{- end }}
				},
				Variants: []genrouterruntime.OutputVariantMetadata{
					{{- range .Output.Variants }}
					{
						StatusCode: {{ .StatusCode }},
						Fields: []genrouterruntime.OutputFieldMetadata{
							{{- range .Fields }}
							{GoName: {{ printf "%q" .GoName }}, Source: {{ printf "%q" .Source }}, Name: {{ printf "%q" .Name }}, Type: {{ printf "%q" .Type }}},
							{{- end }}
						},
					},
					{{- end }}
				},
			},
			Binder: genrouterruntime.BinderMetadata{
				Symbol: {{ printf "%q" (binderSymbol .) }},
				Bind: {{ binderSymbol . }},
			},
		},
		{{- end }}
	},
}
`

var metadataFileTemplate = template.Must(template.New("metadata").Funcs(template.FuncMap{
	"binderSymbol":     binderSymbol,
	"binderStatements": binderStatements,
}).Parse(metadataTemplate))

func MetadataFileName() string { return generatedFileName }

// templateData wraps a PackagePlan with precomputed import flags for the template.
type templateData struct {
	ir.PackagePlan
	NeedsFmt     bool
	NeedsIO      bool
	NeedsStrconv bool
	NeedsStrings bool
	NeedsUUID    bool
}

func computeTemplateData(pkg ir.PackagePlan) templateData {
	d := templateData{PackagePlan: pkg}
	for _, h := range pkg.Handlers {
		if h.Input.Body != nil {
			d.NeedsIO = true
			d.NeedsFmt = true
		}
		for _, f := range h.Input.Fields {
			switch f.Source {
			case "path":
				d.NeedsStrings = true
				d.NeedsFmt = true
			case "query", "header", "cookie":
				d.NeedsFmt = true
			}
			baseType := strings.TrimPrefix(strings.TrimPrefix(f.Type, "*"), "[]")
			switch baseType {
			case "bool", "int", "int8", "int16", "int32", "int64",
				"uint", "uint8", "uint16", "uint32", "uint64",
				"float32", "float64":
				d.NeedsStrconv = true
			case "uuid.UUID", "github.com/google/uuid.UUID":
				d.NeedsUUID = true
			}
		}
	}
	return d
}

func RenderMetadataFile(pkg ir.PackagePlan) ([]byte, error) {
	if pkg.PackageName == "" {
		return nil, fmt.Errorf("package %s has no package name", pkg.ImportPath)
	}
	data := computeTemplateData(pkg)
	var buf bytes.Buffer
	if err := metadataFileTemplate.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("render generated file for %s: %w", pkg.ImportPath, err)
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated file for %s: %w\n%s", pkg.ImportPath, err, buf.String())
	}
	return formatted, nil
}

func OutputPath(pkg ir.PackagePlan) string { return filepath.Join(pkg.Dir, generatedFileName) }

func binderSymbol(handler ir.HandlerPlan) string {
	return "genRouterBind" + exportedIdentifier(handler.HandlerType)
}

func exportedIdentifier(value string) string {
	var b strings.Builder
	capitalizeNext := true
	for _, r := range value {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			if capitalizeNext && r >= 'a' && r <= 'z' {
				r = r - ('a' - 'A')
			}
			capitalizeNext = false
			b.WriteRune(r)
			continue
		}
		capitalizeNext = true
	}
	return b.String()
}

func binderStatements(handler ir.HandlerPlan) ([]string, error) {
	var lines []string
	if handler.Input.Body != nil {
		lines = append(lines, renderBodyAssignmentLines(*handler.Input.Body)...)
	}

	routeSegments := splitPath(handler.Route.Path)
	if hasSourceFields(handler.Input.Fields, "path") {
		lines = append(lines,
			"pathSegments := splitGeneratedPath(req.URL.Path)",
			fmt.Sprintf("if len(pathSegments) != %d {", len(routeSegments)),
			fmt.Sprintf("\treturn input, fmt.Errorf(%q, req.URL.Path)", "request path %q does not match generated pattern "+handler.Route.Path),
			"}",
		)
		for i, segment := range routeSegments {
			if strings.HasPrefix(segment, "{") && strings.HasSuffix(segment, "}") {
				continue
			}
			lines = append(lines,
				fmt.Sprintf("if pathSegments[%d] != %q {", i, segment),
				fmt.Sprintf("\treturn input, fmt.Errorf(%q, req.URL.Path)", "request path %q does not match generated pattern "+handler.Route.Path),
				"}",
			)
		}
	}

	if hasSourceFields(handler.Input.Fields, "query") {
		lines = append(lines, "queryValues := req.URL.Query()")
	}
	if hasSourceFields(handler.Input.Fields, "header") {
		lines = append(lines, "headerValues := req.Header")
	}

	for _, field := range handler.Input.Fields {
		fieldLines, err := renderInputFieldAssignmentLines(field, handler.Route.Path)
		if err != nil {
			return nil, err
		}
		lines = append(lines, fieldLines...)
	}
	return lines, nil
}

func hasSourceFields(fields []ir.InputFieldPlan, source string) bool {
	for _, field := range fields {
		if field.Source == source {
			return true
		}
	}
	return false
}

func renderBodyAssignmentLines(field ir.InputFieldPlan) []string {
	// Extract simple type name for the Decode function lookup
	typeName := field.Type
	if strings.Contains(typeName, ".") {
		parts := strings.Split(typeName, ".")
		typeName = parts[len(parts)-1]
	}

	if strings.HasPrefix(typeName, "*") {
		typeName = strings.TrimPrefix(typeName, "*")
		decodeFuncName := "Decode" + typeName
		return []string{
			"if reqBodyPresentGenerated(req) {",
			"\tbody, err := io.ReadAll(req.Body)",
			"\tif err != nil {",
			fmt.Sprintf("\t\treturn input, fmt.Errorf(%q, err)", "read request body: %w"),
			"\t}",
			fmt.Sprintf("\tdecoded, err := %s(body)", decodeFuncName),
			"\tif err != nil {",
			fmt.Sprintf("\t\treturn input, fmt.Errorf(%q, err)", "decode body into "+field.GoName+": %w"),
			"\t}",
			fmt.Sprintf("\tinput.%s = &decoded", field.GoName),
			"} else {",
			fmt.Sprintf("\tinput.%s = nil", field.GoName),
			"}",
		}
	}

	decodeFuncName := "Decode" + typeName
	return []string{
		"if !reqBodyPresentGenerated(req) {",
		fmt.Sprintf("\treturn input, fmt.Errorf(%q)", "missing request body"),
		"}",
		"body, err := io.ReadAll(req.Body)",
		"if err != nil {",
		fmt.Sprintf("\treturn input, fmt.Errorf(%q, err)", "read request body: %w"),
		"}",
		fmt.Sprintf("decoded, err := %s(body)", decodeFuncName),
		"if err != nil {",
		fmt.Sprintf("\treturn input, fmt.Errorf(%q, err)", "decode body into "+field.GoName+": %w"),
		"}",
		fmt.Sprintf("input.%s = decoded", field.GoName),
	}
}

func renderInputFieldAssignmentLines(field ir.InputFieldPlan, routePath string) ([]string, error) {
	targetExpr := "input." + field.GoName
	switch field.Source {
	case "path":
		segmentIndex, err := routeParamSegmentIndex(routePath, field.Name)
		if err != nil {
			return nil, err
		}
		return renderRequiredAssignmentLines(targetExpr, field.Type, fmt.Sprintf("pathSegments[%d]", segmentIndex), fmt.Sprintf("path parameter %q", field.Name))
	case "query":
		return renderValuesLookupAssignmentLines(targetExpr, field.Type, fmt.Sprintf("queryValues[%q]", field.Name), fmt.Sprintf("query parameter %q", field.Name), true)
	case "header":
		canonicalName := textproto.CanonicalMIMEHeaderKey(field.Name)
		return renderValuesLookupAssignmentLines(targetExpr, field.Type, fmt.Sprintf("headerValues[%q]", canonicalName), fmt.Sprintf("header %q", field.Name), true)
	case "cookie":
		return renderCookieAssignmentLines(targetExpr, field.Type, field.Name, fmt.Sprintf("cookie %q", field.Name))
	default:
		return nil, nil
	}
}

func renderCookieAssignmentLines(targetExpr, typeName, cookieName, label string) ([]string, error) {
	assignmentLines, err := renderOptionalAssignmentLines(targetExpr, typeName, "cookie.Value", label)
	if err != nil {
		return nil, err
	}
	if strings.HasPrefix(typeName, "*") {
		lines := []string{fmt.Sprintf("if cookie, err := req.Cookie(%q); err == nil {", cookieName)}
		for _, line := range assignmentLines {
			lines = append(lines, "\t"+line)
		}
		lines = append(lines,
			"} else if err != http.ErrNoCookie {",
			"\treturn input, err",
			"}",
		)
		return lines, nil
	}

	lines := []string{fmt.Sprintf("if cookie, err := req.Cookie(%q); err == nil {", cookieName)}
	for _, line := range assignmentLines {
		lines = append(lines, "\t"+line)
	}
	lines = append(lines,
		"} else if err == http.ErrNoCookie {",
		fmt.Sprintf("\treturn input, fmt.Errorf(%q)", "missing cookie "+cookieName),
		"} else {",
		"\treturn input, err",
		"}",
	)
	return lines, nil
}

func renderValuesLookupAssignmentLines(targetExpr, typeName, lookupExpr, label string, required bool) ([]string, error) {
	if strings.HasPrefix(typeName, "[]") {
		return renderSliceLookupAssignmentLines(targetExpr, strings.TrimPrefix(typeName, "[]"), lookupExpr, label, required)
	}

	if strings.HasPrefix(typeName, "*") {
		optionalAssignment, err := renderOptionalAssignmentLines(targetExpr, typeName, "values[0]", label)
		if err != nil {
			return nil, err
		}
		lines := []string{fmt.Sprintf("if values, exists := %s; exists && len(values) > 0 {", lookupExpr)}
		for _, line := range optionalAssignment {
			lines = append(lines, "\t"+line)
		}
		lines = append(lines, "}")
		return lines, nil
	}

	requiredAssignment, err := renderRequiredAssignmentLines(targetExpr, typeName, "values[0]", label)
	if err != nil {
		return nil, err
	}
	lines := []string{fmt.Sprintf("if values, exists := %s; exists && len(values) > 0 {", lookupExpr)}
	for _, line := range requiredAssignment {
		lines = append(lines, "\t"+line)
	}
	if !required {
		lines = append(lines, "}")
		return lines, nil
	}
	lines = append(lines,
		"} else {",
		fmt.Sprintf("\treturn input, fmt.Errorf(%q)", "missing "+label),
		"}",
	)
	return lines, nil
}

func renderSliceLookupAssignmentLines(targetExpr, elemType, lookupExpr, label string, required bool) ([]string, error) {
	assignmentLines, err := renderSliceAssignmentLines(targetExpr, elemType, "values", label)
	if err != nil {
		return nil, err
	}
	lines := []string{fmt.Sprintf("if values, exists := %s; exists {", lookupExpr)}
	for _, line := range assignmentLines {
		lines = append(lines, "\t"+line)
	}
	if !required {
		lines = append(lines, "}")
		return lines, nil
	}
	lines = append(lines,
		"} else {",
		fmt.Sprintf("\treturn input, fmt.Errorf(%q)", "missing "+label),
		"}",
	)
	return lines, nil
}

func renderOptionalAssignmentLines(targetExpr, typeName, valueExpr, label string) ([]string, error) {
	if strings.HasPrefix(typeName, "*") {
		return renderPointerAssignmentLines(targetExpr, strings.TrimPrefix(typeName, "*"), valueExpr, label)
	}
	return renderScalarAssignmentLines(targetExpr, typeName, valueExpr, label)
}

func renderRequiredAssignmentLines(targetExpr, typeName, valueExpr, label string) ([]string, error) {
	if strings.HasPrefix(typeName, "[]") {
		return renderSliceAssignmentLines(targetExpr, strings.TrimPrefix(typeName, "[]"), valueExpr, label)
	}
	if strings.HasPrefix(typeName, "*") {
		return renderPointerAssignmentLines(targetExpr, strings.TrimPrefix(typeName, "*"), valueExpr, label)
	}
	return renderScalarAssignmentLines(targetExpr, typeName, valueExpr, label)
}

func renderPointerAssignmentLines(targetExpr, typeName, valueExpr, label string) ([]string, error) {
	parseLines, err := renderScalarParseLines(typeName, valueExpr, label)
	if err != nil {
		return nil, err
	}
	result := append([]string(nil), parseLines...)
	result = append(result, fmt.Sprintf("%s = &parsed", targetExpr))
	return result, nil
}

func renderSliceAssignmentLines(targetExpr, elemType, valuesExpr, label string) ([]string, error) {
	parseLines, err := renderScalarParseLines(elemType, "raw", label)
	if err != nil {
		return nil, err
	}
	lines := []string{fmt.Sprintf("parsedValues := make([]%s, 0, len(%s))", elemType, valuesExpr)}
	lines = append(lines, fmt.Sprintf("for _, raw := range %s {", valuesExpr))
	for _, line := range parseLines {
		lines = append(lines, "\t"+line)
	}
	lines = append(lines, "\tparsedValues = append(parsedValues, parsed)")
	lines = append(lines, "}")
	lines = append(lines, fmt.Sprintf("%s = parsedValues", targetExpr))
	return lines, nil
}

func renderScalarAssignmentLines(targetExpr, typeName, valueExpr, label string) ([]string, error) {
	parseLines, err := renderScalarParseLines(typeName, valueExpr, label)
	if err != nil {
		return nil, err
	}
	result := append([]string(nil), parseLines...)
	result = append(result, fmt.Sprintf("%s = parsed", targetExpr))
	return result, nil
}

func renderScalarParseLines(typeName, valueExpr, label string) ([]string, error) {
	switch typeName {
	case "string":
		return []string{fmt.Sprintf("parsed := %s", valueExpr)}, nil
	case "bool":
		return []string{
			fmt.Sprintf("parsed, err := strconv.ParseBool(%s)", valueExpr),
			"if err != nil {",
			fmt.Sprintf("\treturn input, fmt.Errorf(%q, err)", "invalid "+label+": %w"),
			"}",
		}, nil
	case "int", "int8", "int16", "int32", "int64":
		bits := intBits(typeName)
		return []string{
			fmt.Sprintf("parsedInt, err := strconv.ParseInt(%s, 10, %d)", valueExpr, bits),
			"if err != nil {",
			fmt.Sprintf("\treturn input, fmt.Errorf(%q, err)", "invalid "+label+": %w"),
			"}",
			fmt.Sprintf("parsed := %s(parsedInt)", typeName),
		}, nil
	case "uint", "uint8", "uint16", "uint32", "uint64":
		bits := uintBits(typeName)
		return []string{
			fmt.Sprintf("parsedUint, err := strconv.ParseUint(%s, 10, %d)", valueExpr, bits),
			"if err != nil {",
			fmt.Sprintf("\treturn input, fmt.Errorf(%q, err)", "invalid "+label+": %w"),
			"}",
			fmt.Sprintf("parsed := %s(parsedUint)", typeName),
		}, nil
	case "float32", "float64":
		bits := floatBits(typeName)
		return []string{
			fmt.Sprintf("parsedFloat, err := strconv.ParseFloat(%s, %d)", valueExpr, bits),
			"if err != nil {",
			fmt.Sprintf("\treturn input, fmt.Errorf(%q, err)", "invalid "+label+": %w"),
			"}",
			fmt.Sprintf("parsed := %s(parsedFloat)", typeName),
		}, nil
	case "uuid.UUID", "github.com/google/uuid.UUID":
		return []string{
			fmt.Sprintf("parsed, err := parseGeneratedUUID(%s)", valueExpr),
			"if err != nil {",
			fmt.Sprintf("\treturn input, fmt.Errorf(%q, err)", "invalid "+label+": %w"),
			"}",
		}, nil
	default:
		return nil, fmt.Errorf("unsupported input type %q for generated binder", typeName)
	}
}

func intBits(typeName string) int {
	switch typeName {
	case "int8":
		return 8
	case "int16":
		return 16
	case "int32":
		return 32
	case "int64":
		return 64
	default:
		return 0
	}
}

func uintBits(typeName string) int {
	switch typeName {
	case "uint8":
		return 8
	case "uint16":
		return 16
	case "uint32":
		return 32
	case "uint64":
		return 64
	default:
		return 0
	}
}

func floatBits(typeName string) int {
	if typeName == "float32" {
		return 32
	}
	return 64
}

func routeParamSegmentIndex(routePath, paramName string) (int, error) {
	segments := splitPath(routePath)
	for index, segment := range segments {
		if segment == "{"+paramName+"}" {
			return index, nil
		}
	}
	return 0, fmt.Errorf("path parameter %q not found in route %q", paramName, routePath)
}

func splitPath(path string) []string {
	trimmed := strings.Trim(path, "/")
	if trimmed == "" {
		return nil
	}
	return strings.Split(trimmed, "/")
}
