package emit

import (
	"bytes"
	"fmt"
	"go/format"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/P4elme6ka/gen-router/internal/codegen/ir"
)

const generatedFileName = "zz_gen_router_meta.go"

const metadataTemplate = `// Code generated by gen-router. DO NOT EDIT.
package {{ .PackageName }}

import (
	"encoding/json"
	"fmt"
	"net/http"
	"strconv"
	"strings"

	genrouterruntime "github.com/P4elme6ka/gen-router/internal/codegen/runtime"
)

{{ range .Handlers }}
func {{ binderSymbol . }}(req *http.Request) (any, error) {
	var input {{ .InputType }}
	{{- range binderStatements . }}
	{{ . }}
	{{- end }}
	return input, nil
}

{{ end }}
func splitGeneratedPath(path string) []string {
	trimmed := strings.Trim(path, "/")
	if trimmed == "" {
		return nil
	}
	return strings.Split(trimmed, "/")
}

var GenRouterMetadata = genrouterruntime.PackageMetadata{
	ImportPath: {{ printf "%q" .ImportPath }},
	PackageName: {{ printf "%q" .PackageName }},
	Dir: {{ printf "%q" .Dir }},
	Handlers: []genrouterruntime.HandlerMetadata{
		{{- range .Handlers }}
		{
			HandlerType: {{ printf "%q" .HandlerType }},
			InputType: {{ printf "%q" .InputType }},
			OutputType: {{ printf "%q" .OutputType }},
			Route: genrouterruntime.RouteMetadata{
				Method: {{ printf "%q" .Route.Method }},
				Path: {{ printf "%q" .Route.Path }},
			},
			Input: genrouterruntime.InputMetadata{
				Body: {{- if .Input.Body }}&genrouterruntime.InputFieldMetadata{GoName: {{ printf "%q" .Input.Body.GoName }}, Source: {{ printf "%q" .Input.Body.Source }}, Name: {{ printf "%q" .Input.Body.Name }}, Type: {{ printf "%q" .Input.Body.Type }}} {{- else }}nil{{- end }},
				Fields: []genrouterruntime.InputFieldMetadata{
					{{- range .Input.Fields }}
					{GoName: {{ printf "%q" .GoName }}, Source: {{ printf "%q" .Source }}, Name: {{ printf "%q" .Name }}, Type: {{ printf "%q" .Type }}},
					{{- end }}
				},
			},
			Output: genrouterruntime.OutputMetadata{
				SharedFields: []genrouterruntime.OutputFieldMetadata{
					{{- range .Output.SharedFields }}
					{GoName: {{ printf "%q" .GoName }}, Source: {{ printf "%q" .Source }}, Name: {{ printf "%q" .Name }}, Type: {{ printf "%q" .Type }}},
					{{- end }}
				},
				Variants: []genrouterruntime.OutputVariantMetadata{
					{{- range .Output.Variants }}
					{
						StatusCode: {{ .StatusCode }},
						Fields: []genrouterruntime.OutputFieldMetadata{
							{{- range .Fields }}
							{GoName: {{ printf "%q" .GoName }}, Source: {{ printf "%q" .Source }}, Name: {{ printf "%q" .Name }}, Type: {{ printf "%q" .Type }}},
							{{- end }}
						},
					},
					{{- end }}
				},
			},
			Binder: genrouterruntime.BinderMetadata{
				Symbol: {{ printf "%q" (binderSymbol .) }},
				Bind: {{ binderSymbol . }},
			},
		},
		{{- end }}
	},
}
`

var metadataFileTemplate = template.Must(template.New("metadata").Funcs(template.FuncMap{
	"binderSymbol":     binderSymbol,
	"binderStatements": binderStatements,
}).Parse(metadataTemplate))

func MetadataFileName() string { return generatedFileName }

func RenderMetadataFile(pkg ir.PackagePlan) ([]byte, error) {
	if pkg.PackageName == "" {
		return nil, fmt.Errorf("package %s has no package name", pkg.ImportPath)
	}
	var buf bytes.Buffer
	if err := metadataFileTemplate.Execute(&buf, pkg); err != nil {
		return nil, fmt.Errorf("render generated file for %s: %w", pkg.ImportPath, err)
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated file for %s: %w", pkg.ImportPath, err)
	}
	return formatted, nil
}

func OutputPath(pkg ir.PackagePlan) string { return filepath.Join(pkg.Dir, generatedFileName) }

func binderSymbol(handler ir.HandlerPlan) string {
	return "genRouterBind" + exportedIdentifier(handler.HandlerType)
}

func exportedIdentifier(value string) string {
	var b strings.Builder
	capitalizeNext := true
	for _, r := range value {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			if capitalizeNext && r >= 'a' && r <= 'z' {
				r = r - ('a' - 'A')
			}
			capitalizeNext = false
			b.WriteRune(r)
			continue
		}
		capitalizeNext = true
	}
	return b.String()
}

func binderStatements(handler ir.HandlerPlan) ([]string, error) {
	var lines []string
	if handler.Input.Body != nil {
		lines = append(lines,
			"if req.Body == nil {",
			fmt.Sprintf("\treturn input, fmt.Errorf(%q)", "missing request body"),
			"}",
			"decoder := json.NewDecoder(req.Body)",
			"decoder.DisallowUnknownFields()",
			fmt.Sprintf("if err := decoder.Decode(&input.%s); err != nil {", handler.Input.Body.GoName),
			fmt.Sprintf("\treturn input, fmt.Errorf(%q, err)", "decode body into "+handler.Input.Body.GoName+": %w"),
			"}",
		)
	}
	if hasPathFields(handler.Input.Fields) {
		lines = append(lines,
			"pathSegments := splitGeneratedPath(req.URL.Path)",
			fmt.Sprintf("patternSegments := splitGeneratedPath(%q)", handler.Route.Path),
			"if len(pathSegments) != len(patternSegments) {",
			fmt.Sprintf("\treturn input, fmt.Errorf(%q, req.URL.Path)", "request path %q does not match generated pattern "+handler.Route.Path),
			"}",
		)
	}
	for _, field := range handler.Input.Fields {
		fieldLines, err := renderInputFieldAssignmentLines(field, handler.Route.Path)
		if err != nil {
			return nil, err
		}
		lines = append(lines, fieldLines...)
	}
	return lines, nil
}

func hasPathFields(fields []ir.InputFieldPlan) bool {
	for _, field := range fields {
		if field.Source == "path" {
			return true
		}
	}
	return false
}

func renderInputFieldAssignmentLines(field ir.InputFieldPlan, routePath string) ([]string, error) {
	switch field.Source {
	case "path":
		segmentIndex, err := routeParamSegmentIndex(routePath, field.Name)
		if err != nil {
			return nil, err
		}
		return renderScalarAssignmentLines("input."+field.GoName, field.Type, fmt.Sprintf("pathSegments[%d]", segmentIndex), fmt.Sprintf("path parameter %q", field.Name))
	case "query":
		return renderSourceAssignmentLines("input."+field.GoName, field.Type, fmt.Sprintf("req.URL.Query().Get(%q)", field.Name), fmt.Sprintf("query parameter %q", field.Name))
	case "header":
		return renderSourceAssignmentLines("input."+field.GoName, field.Type, fmt.Sprintf("req.Header.Get(%q)", field.Name), fmt.Sprintf("header %q", field.Name))
	case "cookie":
		if field.Type == "*string" {
			return []string{
				fmt.Sprintf("if cookie, err := req.Cookie(%q); err == nil {", field.Name),
				"\tvalue := cookie.Value",
				fmt.Sprintf("\tinput.%s = &value", field.GoName),
				"} else if err != http.ErrNoCookie {",
				"\treturn input, err",
				"}",
			}, nil
		}
		return []string{
			fmt.Sprintf("if cookie, err := req.Cookie(%q); err == nil {", field.Name),
			fmt.Sprintf("\tinput.%s = cookie.Value", field.GoName),
			"} else if err == http.ErrNoCookie {",
			fmt.Sprintf("\treturn input, fmt.Errorf(%q)", "missing cookie "+field.Name),
			"} else {",
			"\treturn input, err",
			"}",
		}, nil
	default:
		return nil, nil
	}
}

func renderSourceAssignmentLines(targetExpr, typeName, valueExpr, label string) ([]string, error) {
	if strings.HasPrefix(typeName, "*") {
		baseType := strings.TrimPrefix(typeName, "*")
		lines, err := renderPointerAssignmentLines(targetExpr, baseType, label)
		if err != nil {
			return nil, err
		}
		result := []string{fmt.Sprintf("if value := %s; value != \"\" {", valueExpr)}
		for _, line := range lines {
			result = append(result, "\t"+line)
		}
		result = append(result, "}")
		return result, nil
	}
	lines, err := renderScalarAssignmentLines(targetExpr, typeName, "value", label)
	if err != nil {
		return nil, err
	}
	result := []string{fmt.Sprintf("if value := %s; value != \"\" {", valueExpr)}
	for _, line := range lines {
		result = append(result, "\t"+line)
	}
	result = append(result,
		"} else {",
		fmt.Sprintf("\treturn input, fmt.Errorf(%q)", "missing "+label),
		"}",
	)
	return result, nil
}

func renderPointerAssignmentLines(targetExpr, typeName, label string) ([]string, error) {
	switch typeName {
	case "string":
		return []string{"valueCopy := value", fmt.Sprintf("%s = &valueCopy", targetExpr)}, nil
	case "bool":
		return []string{
			"parsed, err := strconv.ParseBool(value)",
			"if err != nil {",
			fmt.Sprintf("\treturn input, fmt.Errorf(%q, err)", "invalid "+label+": %w"),
			"}",
			fmt.Sprintf("%s = &parsed", targetExpr),
		}, nil
	default:
		return nil, fmt.Errorf("unsupported pointer input type %q for generated binder", typeName)
	}
}

func renderScalarAssignmentLines(targetExpr, typeName, valueExpr, label string) ([]string, error) {
	switch typeName {
	case "string":
		return []string{fmt.Sprintf("%s = %s", targetExpr, valueExpr)}, nil
	case "bool":
		return []string{
			fmt.Sprintf("parsed, err := strconv.ParseBool(%s)", valueExpr),
			"if err != nil {",
			fmt.Sprintf("\treturn input, fmt.Errorf(%q, err)", "invalid "+label+": %w"),
			"}",
			fmt.Sprintf("%s = parsed", targetExpr),
		}, nil
	default:
		return nil, fmt.Errorf("unsupported input type %q for generated binder", typeName)
	}
}

func routeParamSegmentIndex(routePath, paramName string) (int, error) {
	segments := splitPath(routePath)
	for index, segment := range segments {
		if segment == "{"+paramName+"}" {
			return index, nil
		}
	}
	return 0, fmt.Errorf("path parameter %q not found in route %q", paramName, routePath)
}

func splitPath(path string) []string {
	trimmed := strings.Trim(path, "/")
	if trimmed == "" {
		return nil
	}
	return strings.Split(trimmed, "/")
}
